name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"



[env.production.vars]
GITHUB_ID = "Ov23liZz2oNXv1KqlpQC"
GITHUB_OWNER = "cibevan"
GITHUB_REPO = "fNav"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://dao.19252025.xyz/api/auth"
NEXT_PUBLIC_API_URL="https://dao.19252025.xyz"

